Repository cse110-fa22-group21/cse110-fa22-group21, pull requests merged in 2022-12, with the labels that each got.

#91 Update add.js to not allow negative minutes/hours and minutes greater than 60
  source/scripts/add.js
Labels: bug, js

#100 Fix the bug of not displaying task by adding the difference field back
  source/scripts/add.js
Labels: bug, js

#105 Meeting Notes Organization + Added meeting notes for e2e fixes #98
  README.md
  admin/meetings/brainstorming/101822-brainstorm.md
  admin/meetings/brainstorming/102222-brainstorm2.md
  admin/meetings/brainstorming/102822-brainstorm3.md
  admin/meetings/crudfeatures/111122-addfeaturemeeting.md
  admin/meetings/crudfeatures/111322-editfeaturemeeting.md
  admin/meetings/crudfeatures/111922-taskdropdownmeeting.md
  admin/meetings/crudfeatures/112022-editfeaturelocalstorage.md
  admin/meetings/crudfeatures/112722-analyticsmeeting.md
  admin/meetings/crudfeatures/112722-logpage.md
  admin/meetings/crudfeatures/112722-storagetesting.md
  admin/meetings/crudfeatures/112722-timestamp.md
  admin/meetings/crudfeatures/112722-timestamp2.md
  admin/meetings/groupkickoff/101522-kickoff.md
  admin/meetings/html&css/110522-cssdevelopment.md
  admin/meetings/html&css/110722-cssdevelopment2.md
  admin/meetings/html&css/111922-responsivenessmeeting.md
  admin/meetings/pipeline/102922-pipeline.md
  admin/meetings/pipeline/103122-pipeline2.md
  admin/meetings/pipeline/110322-pipeline3.md
  admin/meetings/pipeline/111822-pipelinemeeting-JSDocs.md
  admin/meetings/pipeline/112822-pipelinemeeting-JSDocs2.md
  admin/meetings/pipeline/112922-pipelinemeeting-JSDocs3.md
  admin/meetings/pipeline/112922-pipelinemeeting-checkpoint2.md
  admin/meetings/pitch/102622-pitchmeeting.md
  admin/meetings/pitch/102822-pitchmeeting2.md
  admin/meetings/pitch/102922-pitchmeeting3.md
  admin/meetings/retrospective/111322-restrospective.md
  admin/meetings/retrospective/112822-retrospective2.md
  admin/meetings/retrospective/retrospective1-images/Retrium1.png
  admin/meetings/retrospective/retrospective1-images/Retrium2.png
  admin/meetings/retrospective/retrospective1-images/Retrium3.png
  admin/meetings/retrospective/retrospective1-images/Retrium4.png
  admin/meetings/retrospective/retrospective2-images/retrium2.1.png
  admin/meetings/retrospective/retrospective2-images/retriumImg2png.png
  admin/meetings/sprint/111322-sprint-1-review.md
  admin/meetings/sprint/112822-sprint-2-review.md
  admin/meetings/ta/110922-week7-meetingnoteswithta.md
  admin/meetings/ta/111622-week8-meetingnoteswithta.md
  admin/meetings/testing-e2e-unit/113022-e2e-add-edit.md
  admin/meetings/testing-e2e-unit/113022-e2e-edit.md
  admin/meetings/testing-e2e-unit/121022-e2e-homepage.md
  admin/meetings/weekly/110422-postpitchmeeting.md
  admin/meetings/weekly/110922-week7-meetingnotes.md
  admin/meetings/weekly/111122-week7-meetingnotes2.md
  admin/meetings/weekly/111822-week8-team-meeting.md
  admin/meetings/weekly/112322-week9-meetingnotes2.md
  admin/meetings/weekly/112522-week9-meetingnotes.md
  admin/other/lighthouse.png
  admin/other/lighthousereport.pdf
Labels: management

#107 Fixed Invalid Input Number (negative or minutes > 60) When Edit
  source/scripts/add.js
  source/scripts/edit.js
Labels: bug, js

#115 Added an extra check to only be able to add items if less than maxtask fixes #114
  source/scripts/add.js
Labels: bug, testing

#122 Restrict number of task to 100 in analytics page
  source/scripts/analytics.js
  source/scripts/log.js
Labels: js

#120 Created Definition of Done and Meeting Notes fixes #67
  admin/meetings/testing-e2e-unit/120122-e2e-homepage.md
  admin/meetings/weekly/120322-week10-meetingnotes.md
  specs/definitionofdone.md
Labels: documentation, management

#119 E2e delete testing
  admin/meetings/testing-e2e-unit/e2e-tests.md
  source/__tests__/endtoend.test.js
Labels: testing

#124 Wip favicon
  source/html/analytics.html
  source/html/index.html
  source/html/log.html
Labels: graphics

#123 added final video meeting notes
  admin/meetings/120522-video-plan.md
Labels: management

#127 Added onboarding files and updated README fixes #126
  README.md
  admin/onboard.md
Labels: management

#129 log testing
  source/__tests__/endtoend.test.js
Labels: testing

#131 Removed Demo Unit Tests + Cleaned Repo Fixes #130
  admin/meetings/finalvideo/120522-video-plan.md
  source/__tests__/endtoend.test.js
  source/__tests__/sum.test.js
  source/html/index.html
  source/html/log.html
  source/scripts/sum.js
Labels: management

#133 adjusted home page add button
  source/html/index.html
  source/images/add-button.svg
  source/styles/index.css
  source/styles/page.css
Labels: bug, graphics
