Repository cse110-fa22-group21/cse110-fa22-group21, pull requests merged in 2022-11, with the labels that each got.

#18 Fixed script location
  .github/workflows/js_lint.yml
Labels: js, pipeline

#19 Merge CSS changes
  admin/branding/edit-icon.svg
  admin/branding/team21-nobg.png
  analytics.html
  images/edit-button.jpg
  index.html
  log.html
  style.css
  styles/colors.css
  styles/footer.css
  styles/header.css
  styles/index.css
  styles/page.css
Labels: css, graphics

#29 Pushed Meeting Notes For This Week
  admin/meetings/102822-brainstorm3.md
  admin/meetings/110922-week7-meetingnotes.md
  admin/meetings/110922-week7-meetingnoteswithta.md
  admin/meetings/111122-addfeaturemeeting.md
  admin/meetings/111122-week7-meetingnotes2.md
Labels: management

#37 Checkpoint 1 Items - missing video Fixes #30
  admin/cpipeline/CodingManifest.md
  admin/cpipeline/githubworkflows.md
  admin/cpipeline/phase1.drawio.png
  admin/cpipeline/phase1.md
Labels: management, pipeline

#34 Sprint + Retrospective Meeting Notes Fixes #33
  admin/meetings/111322-restrospective.md
  admin/meetings/retrospective-images/Retrium1.png
  admin/meetings/retrospective-images/Retrium2.png
  admin/meetings/retrospective-images/Retrium3.png
  admin/meetings/retrospective-images/Retrium4.png
  specs/adrs/102622-ProblemSolutionFeatures.md
Labels: management

#41 move font settings to page.css
  styles/index.css
  styles/page.css
Labels: css, refactor

#45 Wip storage
  images/complete-icon.png
  index.html
  scripts/add.js
  scripts/edit.js
  styles/index.css
Labels: feature, css, js

#62 Feature delete
  index.html
  scripts/add.js
  scripts/delete.js
  scripts/edit.js
  styles/index.css
Labels: feature, js

#50 Implemented custom css and some html changes to make the page work on mobile devices
  admin/meetings/111922-responsivenessmeeting.md
  source/html/analytics.html
  source/html/index.html
  source/html/log.html
  source/images/team21-nobg.png
  source/styles/header.css
  source/styles/index.css
  source/styles/mobile.css
Labels: feature, css

#66 Completed Task Drop Down + meeting notes Fixes #55#
  admin/meetings/111922-taskdropdownmeeting.md
  source/scripts/add.js
  source/styles/colors.css
  source/styles/index.css
  source/styles/page.css
Labels: html, css, js

#65 Add options into .prettierrc.json
  .prettierrc.json
Labels: pipeline

#68 Edit Feature Local Storage Completed Fixes #44
  admin/meetings/112022-editfeaturelocalstorage.md
  source/html/index.html
  source/scripts/add.js
  source/scripts/delete.js
  source/scripts/edit.js
  source/styles/index.css
Labels: feature, js

#83 Github pages automation, closes #82
  .github/workflows/setup_pages.yml
  source/html/analytics.html
  source/html/index.html
  source/html/log.html
Labels: html, pipeline, urgent

#76 Feature start end timestamps
  admin/meetings/111322-restrospective.md
  admin/meetings/112722-timestamp.md
  admin/meetings/112722-timestamp2.md
  admin/meetings/112822-retrospective2.md
  admin/meetings/112822-sprint-2-review.md
  admin/meetings/retrospective1-images/Retrium1.png
  admin/meetings/retrospective1-images/Retrium2.png
  admin/meetings/retrospective1-images/Retrium3.png
  admin/meetings/retrospective1-images/Retrium4.png
  admin/meetings/retrospective2-images/retrium2.1.png
  source/html/index.html
  source/scripts/add.js
  source/scripts/edit.js
  source/styles/index.css
Labels: feature, js

#89 Implemented JSDoc generation with github pages on push to main
  .github/workflows/jsdocs.yml
  .github/workflows/setup_pages.yml
  .husky/pre-commit
  .prettierignore
  .prettierrc.json
  package-lock.json
  package.json
  source/jsdoc.json
Labels: documentation, feature, js, pipeline, urgent

#77 Fixes #23
  admin/meetings/112722-logpage.md
  admin/meetings/112822-retrospective2.md
  source/html/index.html
  source/html/log.html
  source/scripts/add.js
  source/scripts/delete.js
  source/scripts/log.js
  source/styles/footer.css
  source/styles/index.css
Labels: feature, js

#92 Create prettier.yml
  .eslintrc.js
  .github/workflows/prettier.yml
  .prettierignore
  .prettierrc.json
  README.md
  source/html/analytics.html
  source/html/index.html
  source/html/log.html
  source/scripts/add.js
  source/scripts/delete.js
  source/scripts/edit.js
  source/scripts/log.js
  source/styles/colors.css
  source/styles/footer.css
  source/styles/header.css
  source/styles/index.css
  source/styles/mobile.css
  source/styles/page.css
Labels: pipeline, refactor

#85 Display Expected, Actual Time, Emoji on Analytic Page
  source/html/analytics.html
  source/images/happy.png
  source/images/sad.png
  source/scripts/add.js
  source/scripts/analytics.js
Labels: js, graphics
